import "./globals.css";
import { Header } from "@ui/components";
import { Roboto } from "next/font/google";
import type { Metadata } from "next";

const roboto = Roboto({
  variable: "--preferred-font",
});

export const metadata: Metadata = {
  title: "Hello World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Header isHome />
        {children}
      </body>
    </html>
  );
}
